### PR TITLE
WIP - rewrite

### PR DESCRIPTION
**Pull request by nearlySplat**
Huge rewrite, poggers.

Striked-through items are N/A

## To-do

- [x] <s>configurable prefixes</s> 
- [x] update README to actually comply with the license
- [ ] add automatic deployer (fork people: set a webhook to this uri)
- [ ] caught bugs now post to [sentry], an online bug tracker
- [ ] move to [i18next], an internationalisation framework
- [ ] add module aliasing so no more `../../../../src` 
- [ ] bump discord.js—update to newest changes
- [x] about command now shows 'Hi, I'm a bot.'
- [x] fix markdown in debug command
- [x] die command now says '\*light turns off*'
- [ ] restore hewp command (shows an uwu-ified version of the 'help' response)
- [ ] </s>added hide button next to the delete button </s>
- [ ] add slashify command, which is just base 1 but /
- [ ] <s>change source command to only work for commands, *and not be able to leak my .env file*</s>
- [ ] <s>add slashsync alias for syncslash (I always forget which is which lmao)</s> (not needed for slash command only rewrite (also I added a slash command syncer)
- [x] use classes for listeners and commands
- [ ] add prune and textedit commands

[sentry]: https://sentry.io
[i18next]: https://www.i18next.com

### CODE REVIEW

**Comment by nearlySplat** [comment]
oh god

**Comment by nearlySplat** [comment]
oh lord this is gonna be a tonne of fun to review

**Review by nearlySplat — COMMENTED** [review]
alright, todo is finished for now:tm:

**Comment by nerrixDE** [comment]
sus

**Comment by nearlySplat** [comment]
oh i forgot this existed

**Pull request merged**
